### ISSUE TITLE
Color themes doesn't show up in preferences menu

### ISSUE THREAD

**Issue by teaecetyrannis** [sebshader/color-themes-plugin#2]
I get the post "color-themes: no ::pd_colors array: skipping". Why could this be happening? I checked the .tcl file and that array is supposed to exist.

**Comment by sebshader** [comment]
@teaecetyrannis currently the color themes plugin must be used w/ pd-next, my pd fork https://github.com/sebshader/pdnext/releases
at some point in the future it would also work w/ pd vanilla if the relevant PR is accepted

**Comment by teaecetyrannis** [comment]
Oh, sorry! I can see I missed that, will definitely be trying it. Thanks for answering.
